title: Home
description: Senior Data Scientist | Edge AI | Production Grade ML
author: Bahman Roostaei
theme: minima
markdown: kramdown

baseurl: "/bahmanroostaei.github.io"  # 👈 Add this line

header_pages:
  - index.md
  - blog.md
  - personal.md
  - news.md
