title: Home
description: Senior Data Scientist | Edge AI | Production Grade Machine Learning 
author: Bahman Roostaei
email: bmn7891@gmail.com
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - blog.md
  - personal.md
